project:
  type: default
  output-dir: docs

format:
  revealjs:
    title: "Digitalization and Datacenter Interplay"
    subtitle: "Datacenter Technical Seminar (*Postgrunn - University of South-Eastern Norway - September 2025*)"
    footer: "Datacenter Technical Seminar (*Postgrunn - University of South-Eastern Norway - September 2025*)"
    author: 
      - name: "Jordi Mateo Fornés"
        affiliation: "Distributed Computing Group, University of Lleida"
    title-slide-attributes:
      data-notes: | 
        Good morning, everyone. I want to start by thanking Professor Sambeet for inviting me and giving me the opportunity to speak with you today. We first met many years ago at NTNU in Trondheim, where we were both doing our PhD research stay. I was focused on computer science, and he was focused on power systems. Since then, we've have continued to collaborate in the field of Energy Informatics. That's why I'm here with you today.
    theme: simple
    transition: fade
    slide-number: true
    incremental: true
    chalkboard: false
    pointer: flase
    toc: false
    toc-depth: 1
    bibliography: bib.bib

execute:
  freeze: auto
  echo: false